### ISSUE TITLE
Modifying patient comment only misses save symbol

### ISSUE THREAD

**Issue by col-panic** [rgwch/webelexis#8]
If I modify a patients comment only, the save symbol is not shown. I have to modify an additional attribute in order for it to be presented!

**Comment by rgwch** [comment]
Indeed. I forgot the blur.trigger. Should be fixed now.

**Comment by rgwch** [comment]
Is it ok now? If so, please close issue

**Comment by col-panic** [comment]
Yes, it's working now - thanks!
